<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FAQ — FabricAI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @vite(['resources/css/app.css','resources/js/app.js'])
</head>

<body class="bg-cream-50 text-ink font-sans antialiased overflow-x-hidden">
@include('layouts.navigation')

<!-- ================= HERO ================= -->
<section class="pt-36 pb-16 text-center">
    <div class="max-w-3xl mx-auto px-6">
        <p class="text-sm font-medium tracking-widest uppercase text-ink-muted mb-4">Support</p>
        <h1 class="font-serif text-5xl mb-6">
            Frequently Asked Questions
        </h1>
        <p class="text-ink-muted text-lg">
            Everything you need to know about FabricAI and how it works.
        </p>
    </div>
</section>

<!-- ================= FAQ SECTION ================= -->
<section class="pb-32">
    <div class="max-w-3xl mx-auto px-6 space-y-px bg-cream-300">
        @php
            $faqs = [
                [
                    'q' => 'Why should I use FabricAI instead of alternatives like ChatGPT or Gemini?',
                    'a' => 'Unlike broader AI models, FabricAI is entirely designed to create suitable designs for clothing, generating clean, visible and attractive images with adapted background to fit any type of clothes. FabricAI is highly trained on Printify print-on-demand catalog, creating images with the perfect size and quality that Printify requests.'
                ],
                [
                    'q' => 'Is FabricAI a mockup generator?',
                    'a' => 'No. Unlike those apps, FabricAI creates the product itself, not an image to use as a guide. The designs generated by FabricAI are already finished products ready for selling.'
                ],
                [
                    'q' => 'What do I do with my designs?',
                    'a' => 'FabricAI creates fully designed models ready to sell with the Printify API with a single prompt, so you just need to publish the model on your store.'
                ],
                [
                    'q' => 'Is it legal to sell clothes with AI generated images?',
                    'a' => 'It is completely legal as long as you don’t sell copyrighted material. That is why we highly advice our users to not generate this type of content. Additionally, FabricAI is tuned to never generate recognizable human faces.'
                ],
                [
                    'q' => 'How much does this cost?',
                    'a' => 'FabricAI offers various plans adapted to all kinds of users. We also offer some free credits so everyone can try it out before looking for a plan.'
                ],
            ];
        @endphp

        @foreach($faqs as $index => $faq)
        <div
            x-data="{ open: false }"
            x-intersect.once="$el.classList.remove('opacity-0','translate-y-4')"
            class="opacity-0 translate-y-4 transition-all duration-500
                   bg-white"
        >
            <!-- Question -->
            <button
                @click="open = !open"
                class="w-full flex justify-between items-center px-8 py-6 text-left group"
            >
                <span class="font-medium text-ink text-base pr-4">
                    {{ $faq['q'] }}
                </span>
                <span
                    :class="open ? 'rotate-45' : ''"
                    class="text-ink-muted text-xl transition-transform duration-300 shrink-0">
                    +
                </span>
            </button>
            <!-- Answer -->
            <div
                x-show="open"
                x-collapse
                x-cloak
                class="px-8 pb-6 text-ink-muted text-sm leading-relaxed"
            >
                {{ $faq['a'] }}
            </div>
        </div>
        @endforeach
    </div>
</section>

<!-- ================= CTA ================= -->
<section class="bg-ink text-white section-padding">
    <div class="max-w-2xl mx-auto px-6 text-center">
        <h2 class="font-serif text-4xl mb-4">Still have questions?</h2>
        <p class="text-white/60 text-lg mb-10">
            Jump right in and experience FabricAI for yourself — no commitment needed.
        </p>
        <a href="{{ url('/designs') }}"
           class="inline-block px-10 py-4 bg-white text-ink text-sm font-medium tracking-wide uppercase
                  hover:bg-cream-100 transition-colors duration-300">
            Try FabricAI now
        </a>
    </div>
</section>

@include('layouts.footer')

</body>
</html>
