substitutions:
  _REGION: europe-west1
  _SERVICE: proyectof
  _IMAGE: gcr.io/gen-lang-client-0352261941/proyectof
  _APP_KEY: base64:4ZO8qcHIzKh1hJ4GaostSEMwI/P2XqphnZ49yXcFPB0=
  _GEMINI_BACKEND_URL: https://fabricai-278322460825.europe-west1.run.app/
  _GEMINI_BACKEND_TOKEN: ""

steps:
  # Limpiar caché de Laravel y mostrar APP_URL
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - -c
      - |
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear
        echo "APP_URL: $(php -r 'echo env(\"APP_URL\");')"

  # Limpiar y construir assets frontend
  - name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        rm -rf public/build
        npm install
        npm run build

  # Construir imagen Docker
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]

  # Subir imagen al registro
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  # Desplegar a Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_IMAGE
      - --region=$_REGION
      - --allow-unauthenticated
      - --set-env-vars=APP_ENV=production,APP_DEBUG=false,SESSION_DRIVER=database,CACHE_STORE=array,APP_KEY=$_APP_KEY,GEMINI_BACKEND_URL=$_GEMINI_BACKEND_URL,GEMINI_BACKEND_TOKEN=$_GEMINI_BACKEND_TOKEN,GEMINI_BACKEND_PATH=/generate,GEMINI_BACKEND_AUTH_HEADER=none,GEMINI_BACKEND_METHOD=POST,DB_CONNECTION=mysql,DB_HOST=/cloudsql/gen-lang-client-0352261941:europe-west1:fabricai-sql,DB_PORT=3306,DB_DATABASE=Fabricai,DB_USERNAME=fabricai,DB_PASSWORD=fabricai,QUEUE_CONNECTION=sync,APP_URL=https://proyectof-278322460825.europe-west1.run.app
      - --add-cloudsql-instances=gen-lang-client-0352261941:europe-west1:fabricai-sql

images:
  - $_IMAGE

options:
  logging: CLOUD_LOGGING_ONLY
