substitutions:
  _REGION: europe-west1
  _SERVICE: proyectof
  _IMAGE: gcr.io/$PROJECT_ID/proyectof

steps:
  # Construir imagen Docker
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]

  # Subir imagen al registro
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  # Desplegar a Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_IMAGE
      - --region=$_REGION
      - --allow-unauthenticated
      - --set-env-vars=APP_ENV=production,APP_DEBUG=false,SESSION_DRIVER=cookie,CACHE_STORE=array,APP_KEY=$$APP_KEY,GEMINI_BACKEND_URL=$$GEMINI_BACKEND_URL,GEMINI_BACKEND_TOKEN=$$GEMINI_BACKEND_TOKEN,GEMINI_BACKEND_PATH=/generate,GEMINI_BACKEND_AUTH_HEADER=none,GEMINI_BACKEND_METHOD=POST
    secretEnv:
      - APP_KEY
      - GEMINI_BACKEND_URL
      - GEMINI_BACKEND_TOKEN

# Configuración de secrets desde Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/APP_KEY/versions/latest
      env: APP_KEY
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_BACKEND_URL/versions/latest
      env: GEMINI_BACKEND_URL
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_BACKEND_TOKEN/versions/latest
      env: GEMINI_BACKEND_TOKEN

images:
  - $_IMAGE

options:
  logging: CLOUD_LOGGING_ONLY
