substitutions:
  _REGION: europe-west1
  _SERVICE: proyectof
  _PROJECT_ID: gen-lang-client-0352261941
  _IMAGE: gcr.io/gen-lang-client-0352261941/proyectof
  _APP_KEY: base64:4ZO8qcHIzKh1hJ4GaostSEMwI/P2XqphnZ49yXcFPB0=
  _GEMINI_BACKEND_URL: https://fabricai-278322460825.europe-west1.run.app/
  _GEMINI_BACKEND_TOKEN: ""

steps:
  # Construir imagen Docker
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]

  # Subir imagen al registro
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  # Desplegar a Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_IMAGE
      - --region=$_REGION
      - --allow-unauthenticated
      - --set-env-vars=APP_ENV=production,APP_DEBUG=false,SESSION_DRIVER=cookie,CACHE_STORE=array,APP_KEY=$_APP_KEY,GEMINI_BACKEND_URL=$_GEMINI_BACKEND_URL,GEMINI_BACKEND_TOKEN=$_GEMINI_BACKEND_TOKEN,GEMINI_BACKEND_PATH=/generate,GEMINI_BACKEND_AUTH_HEADER=none,GEMINI_BACKEND_METHOD=POST

images:
  - $_IMAGE

options:
  logging: CLOUD_LOGGING_ONLY
